spring:
  kafka:
    consumer:
      bootstrap-servers: node1:9092,node2:9092,node3:9092
      group-id: redisGroup
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 10
  redis:
    host: app
    port: 6379
    password: touchspring
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0


